# Generated by Django 2.1.1 on 2018-10-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181016_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tool')),
            ],
        ),
    ]
