# Generated by Django 2.1.1 on 2018-10-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20181017_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolrating',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Tool'),
            preserve_default=False,
        ),
    ]
