# Generated by Django 2.1.1 on 2018-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181017_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tool_category',
            field=models.CharField(choices=[('1', '-'), ('2', 'Carpentry & Woodworking'), ('3', 'Electrical & Soldering'), ('4', 'Plumbing'), ('5', 'Lawn & Garden'), ('6', 'Miscellaneous')], default='1', max_length=1),
        ),
    ]
