# Generated by Django 2.1.1 on 2018-10-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20181017_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tool_category',
            field=models.IntegerField(choices=[('1', '-'), ('2', 'Carpentry & Woodworking'), ('3', 'Electrical & Soldering'), ('4', 'Plumbing'), ('5', 'Lawn & Garden'), ('6', 'Miscellaneous')], default='1'),
        ),
        migrations.AlterField(
            model_name='toolrating',
            name='rating',
            field=models.IntegerField(choices=[('1', '-'), ('2', 'Broken'), ('3', 'Poor'), ('4', 'Ok'), ('5', 'Good'), ('6', 'Excellent')], default='1'),
        ),
    ]
