# Generated by Django 2.1.1 on 2018-10-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_tool_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tool',
            new_name='user',
        ),
    ]
