# Generated by Django 2.1.1 on 2018-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20181018_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tool',
        ),
        migrations.AddField(
            model_name='category',
            name='tools',
            field=models.ManyToManyField(to='main_app.Tool'),
        ),
    ]
