# Generated by Django 2.1.1 on 2018-10-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20181018_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolrating',
            name='date',
        ),
        migrations.RemoveField(
            model_name='toolrating',
            name='tool',
        ),
        migrations.AddField(
            model_name='toolrating',
            name='tool',
            field=models.ManyToManyField(to='main_app.Tool'),
        ),
    ]
